#!/command/with-contenv bash

source /assets/functions/00-container
prepare_service defaults 10-tinc
PROCESS_NAME="tinc-squid"

check_container_initialized
check_service_initialized init 10-tinc

liftoff
/usr/sbin/squid -NYCd 1 -f /etc/squid/squid.conf